update github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,10 +94,15 @@ jobs:
     - name: Check for vulnerable packages
       run: |
         dotnet list package --vulnerable --format json > vulnerabilities.json
-        high_severity_count=$(jq '[.projects[].frameworks[].vulnerablePackages[] | select(.severity == "High")] | length' vulnerabilities.json)
-        if [ "$high_severity_count" -gt 0 ]; then
-          echo "##[error]High severity vulnerabilities found: $high_severity_count"
-          exit 1
+        vulnerable_count=$(jq '[.projects[].frameworks[].vulnerablePackages[]] | length' vulnerabilities.json)
+        if [ "$vulnerable_count" -eq 0 ]; then
+          echo "No vulnerable packages found."
         else
-          echo "No high severity vulnerabilities found."
+          high_severity_count=$(jq '[.projects[].frameworks[].vulnerablePackages[] | select(.severity == "High")] | length' vulnerabilities.json)
+          if [ "$high_severity_count" -gt 0 ]; then
+            echo "##[error]High severity vulnerabilities found: $high_severity_count"
+            exit 1
+          else
+            echo "No high severity vulnerabilities found."
+          fi
         fi
