update github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,16 +77,15 @@ jobs:
     - name: Check for vulnerable packages
       run: |
         dotnet list package --vulnerable --format json > vulnerabilities.json
-        cat vulnerabilities.json
-        vulnerable_packages=$(jq -r '[.projects[].frameworks[]?.vulnerablePackages // []] | add | .[]?' vulnerabilities.json)
-        if [ -z "$vulnerable_packages" ]; then
-          echo "No vulnerable packages found."
+        vulnerable_packages=$(jq -r '[.projects[].frameworks[]?.topLevelPackages[]?.vulnerabilities // []] | add' vulnerabilities.json)
+        if [ -z "$vulnerable_packages" ] || [ "$vulnerable_packages" = "null" ]; then
+            echo "No vulnerable packages found."
         else
-          high_severity_count=$(echo "$vulnerable_packages" | jq '[.[] | select(.severity == "High")] | length')
-          if [ "$high_severity_count" -gt 0 ]; then
-            echo "##[error]High severity vulnerabilities found: $high_severity_count"
-            exit 1
-          else
-            echo "No high severity vulnerabilities found."
-          fi
+            high_severity_count=$(echo "$vulnerable_packages" | jq -r '[.[] | select(.severity == "High")] | length')
+            if [ "$high_severity_count" -gt 0 ]; then
+                echo "##[error]High severity vulnerabilities found: $high_severity_count"
+                exit 1
+            else
+                echo "No high severity vulnerabilities found."
+            fi
         fi
