update github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,6 +55,11 @@ jobs:
         mkdir -p ./coverage/
         dotnet test MvcMovieTests/MvcMovieTests.csproj --collect:"XPlat Code Coverage" /p:CoverletOutput=$(pwd)/coverage/ /p:CoverletOutputFormat=cobertura --logger "trx;LogFileName=test-results.trx"
         # mv $(find MvcMovieTests/TestResults -name 'coverage.cobertura.xml' | head -n 1) coverage/coverage.cobertura.xml
+
+        if [ ! -f $(pwd)/coverage/coverage.cobertura.xml ]; then
+          echo "Coverage file not found after tests"
+          exit 1
+        fi
       env:
         sqlOptions: ${{ env.SQL_OPTIONS }}
 
@@ -67,7 +72,7 @@ jobs:
     - name: Check Coverage Threshold
       run: |
         set -e
-        LINE_COVERAGE=$(xmllint --xpath 'string(//coverage/@line-rate)' coverage/coverage.cobertura.xml | awk '{print $1 * 100}')
+        LINE_COVERAGE=$(xmllint --xpath 'string(//coverage/@line-rate)' $(pwd)/coverage//coverage.cobertura.xml | awk '{print $1 * 100}')
         if (( $(echo "$LINE_COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
           echo "Line Coverage is below threshold"
           exit 1
